//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TriggerScriptWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(TriggerScript), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("LuaOnTriggerEnter", get_LuaOnTriggerEnter, set_LuaOnTriggerEnter);
		L.RegVar("LuaOnTriggerExit", get_LuaOnTriggerExit, set_LuaOnTriggerExit);
		L.RegVar("LuaOnTriggerStay", get_LuaOnTriggerStay, set_LuaOnTriggerStay);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaOnTriggerEnter(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TriggerScript obj = (TriggerScript)o;
			LuaInterface.LuaFunction ret = obj.LuaOnTriggerEnter;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index LuaOnTriggerEnter on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaOnTriggerExit(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TriggerScript obj = (TriggerScript)o;
			LuaInterface.LuaFunction ret = obj.LuaOnTriggerExit;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index LuaOnTriggerExit on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaOnTriggerStay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TriggerScript obj = (TriggerScript)o;
			LuaInterface.LuaFunction ret = obj.LuaOnTriggerStay;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index LuaOnTriggerStay on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaOnTriggerEnter(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TriggerScript obj = (TriggerScript)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaOnTriggerEnter = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index LuaOnTriggerEnter on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaOnTriggerExit(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TriggerScript obj = (TriggerScript)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaOnTriggerExit = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index LuaOnTriggerExit on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaOnTriggerStay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TriggerScript obj = (TriggerScript)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaOnTriggerStay = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index LuaOnTriggerStay on a nil value" : e.Message);
		}
	}
}

